services:
    postgres:
        container_name: "femgocrud-db"
        image: postgres:17-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: femgocrud
        ports:
            - "5432:5432"
        volumes:
            - "./var/postgres_data:/var/lib/postgresql/data:rw"
        restart: unless-stopped
